default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#  username: <%= ENV['DB_NAME'] %>
#  password: <%= ENV['DB_PWD'] %>

development:
  <<: *default
  database: dummy_development

test:
  <<: *default
  database: dummy_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
